target 'iosApp' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'shared', :path => '../shared'
  pod 'KMPNativeCoroutinesAsync', '1.0.0-ALPHA-13'    # Swift Concurrency implementation
  pod 'KMPNativeCoroutinesCombine', '1.0.0-ALPHA-13'  # Combine implementation
  pod 'KMPNativeCoroutinesRxSwift', '1.0.0-ALPHA-13'  # RxSwift implementation
  pod 'KMMViewModelSwiftUI', '1.0.0-ALPHA-12'
end